spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${MYSQL_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PW}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB #미디어 최대 크기 지정

  security:
    user:
      name: test
      password: 1234

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      hibernate:
        SQL: debug

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false